# Increase heap size to 4GB (or 2048M for a middle ground)
org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=1G -XX:+UseParallelGC -Dfile.encoding=UTF-8

# Enable parallel execution to speed up builds
org.gradle.parallel=true

# Enable the build cache to reuse results from previous builds
org.gradle.caching=true

# Keep the Gradle daemon alive for faster subsequent builds
org.gradle.daemon=trueandroid.newDsl=false

android.useAndroidX=true
android.enableJetifier=true